# Generated by Django 5.2.8 on 2025-12-13 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Re", "Received"),
                            ("O", "Open"),
                            ("P", "In progess"),
                            ("R", "Resolved"),
                            ("C", "Closed"),
                        ],
                        default="Re",
                        max_length=2,
                    ),
                ),
                ("photo", models.ImageField(upload_to="FixMyStreet/")),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.user"
                    ),
                ),
            ],
        ),
    ]
