# Generated by Django 5.2.8 on 2025-12-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_problem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="problem",
            old_name="user_id",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="problem",
            name="photo",
            field=models.ImageField(upload_to="problems/"),
        ),
    ]
