# Generated by Django 5.2.8 on 2025-12-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_user_id_problem_user_alter_problem_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="photo",
            field=models.ImageField(upload_to=""),
        ),
    ]
