# Generated by Django 5.2.8 on 2025-12-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_problem_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="photo",
            field=models.URLField(),
        ),
    ]
