# Generated by Django 5.2.8 on 2025-12-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_problem_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="photo_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="problem",
            name="photo",
            field=models.ImageField(upload_to=""),
        ),
    ]
