# Generated by Django 5.2.8 on 2025-12-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_problem_photo_url_alter_problem_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="problem",
            name="photo",
        ),
        migrations.AlterField(
            model_name="problem",
            name="photo_url",
            field=models.URLField(default="-"),
            preserve_default=False,
        ),
    ]
